package by.bsuir.exchange.tagable;

public enum RepositoryTagEnum {
    ACTOR_REPOSITORY, DELIVERY_REPOSITORY, IMAGE__REPOSITORY,
    OFFER_REPOSITORY, RELATION_REPOSITORY, USER_REPOSITORY,
    WALLET_REPOSITORY
}
