package by.bsuir.exchange.command;

public enum CommandEnum {
    LOGIN,
    LOGOUT,
    REGISTER,
    UPDATE_PROFILE,
    UPDATE_PROFILE_CLIENT,
    UPDATE_PROFILE_COURIER,
    UPDATE_OFFER,
    UPDATE_AVATAR,
    GET_USERS,
    DELETE_USER,
    GET_PROFILE,
    GET_COURIERS,
    GET_OFFERS,
    GET_DELIVERIES,
    GET_IMAGE,
    REQUEST_DELIVERY,
    FINISH_DELIVERY,
    SET_LOCALE,
    LIKE_COURIER,
    EMPTY
}
